name: stocks_app
description: A Flutter stocks application with news feed
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.14
  intl: ^0.20.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/stock_logo.jpg"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/stock_logo_splash.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
